export function randomQuestion() {
  return Questions[Math.trunc(Math.random() * Questions.length)];
}

export function isCorrectAnswer(question, answer) {
  return question.correct_answers[answer + "_correct"] === "true";
}

export const Questions = [
  {
    id: 152,
    question: "What is the correct HTML element for playing audio files?",
    description: null,
    answers: {
      answer_a: "<audio>",
      answer_b: "<sound>",
      answer_c: "<mp3>",
      answer_d: '<type "mpr3">',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "",
    difficulty: "Easy",
  },
  {
    id: 601,
    question:
      "If the variable $var1 is set to 10 and the $var2 is set to the character var1, what's the value of $$var2?",
    description: null,
    answers: {
      answer_a: "$$var2 contains the value 1.",
      answer_b: "$$var2 contains the value 5",
      answer_c: "$$var2 contains the value 20",
      answer_d: "$$var2 contains the value 10.",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "PHP" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 1057,
    question:
      "What do you need to specify in your Ansible playbook to stop gathering facts?",
    description: null,
    answers: {
      answer_a: "facts_gathering: no",
      answer_b: "gather: no",
      answer_c: "facts: no",
      answer_d: "gather_facts: no",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "DevOps" }],
    category: "DevOps",
    difficulty: "Easy",
  },
  {
    id: 541,
    question: "What is the use of Scalable Vector Graphics (SVG) in HTML5?",
    description: null,
    answers: {
      answer_a:
        "Scalable Vector Graphics (SVG) is the part of the vector-based family of graphics. There are various forms of Raster-based graphics available that stores the color definition for each pixel in an array of data.",
      answer_b:
        "Scalable Vector Graphics (SVG) is the part of the colored-based family of graphics. There are various forms of Raster-based graphics available that stores the design definition for each pixel in an array of data.",
      answer_c: null,
      answer_d: null,
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Hard",
  },
  {
    id: 21,
    question:
      "Which of the following is a text editor that can be used in command mode to edit files on a Linux system?",
    description: null,
    answers: {
      answer_a: "vi or vim",
      answer_b: "lsof",
      answer_c: "open",
      answer_d: "edit",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "Linux" }],
    category: "Linux",
    difficulty: "Easy",
  },
  {
    id: 329,
    question: "How can you change table sctructure after it was created?",
    description: null,
    answers: {
      answer_a: "CHANGE TABLE",
      answer_b: "MODIFY TABLE",
      answer_c: "ALTER TABLE",
      answer_d: "UPDATE TABLE",
      answer_e: "It's not possible to change the structure",
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "MySQL" }],
    category: "SQL",
    difficulty: "Easy",
  },
  {
    id: 930,
    question: "How can a company deal with a monolithic codebase issue?",
    description: null,
    answers: {
      answer_a:
        "By transitioning from a monolithic codebase to a microservice design so that different microservices can be classified as containers.",
      answer_b:
        "By building a large Docker image containing the monolithic codebase and deploying it as a single container to Kubernetes",
      answer_c: null,
      answer_d: null,
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: "Kubernetes" }],
    category: "DevOps",
    difficulty: "Easy",
  },
  {
    id: 897,
    question: "Replication Controllers and Deployment Controllers are part of",
    description: null,
    answers: {
      answer_a: "API Controller Manager",
      answer_b: "Etcd manager",
      answer_c: "Master Controller Manager",
      answer_d: "Kubeadm",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [{ name: "Kubernetes" }],
    category: "DevOps",
    difficulty: "Easy",
  },
  {
    id: 463,
    question:
      "Which Tag is used if you want to indicate the importance of the phrase?",
    description: null,
    answers: {
      answer_a: "<h1>",
      answer_b: "<h2>",
      answer_c: "<strong>",
      answer_d: "<em>",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 1060,
    question: "Which of the following are true for routes in Laravel?",
    description: null,
    answers: {
      answer_a: "You can not pass any arguments to your routes.",
      answer_b:
        "Routes can point to a method on a controller and also dictate which HTTP methods are able to hit that URI.",
      answer_c:
        "A route is an endpoint specified by a URI (Uniform Resource Identifier).",
      answer_d: "Routes can only handle GET requests",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "true",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "Laravel" }],
    category: "Code",
    difficulty: "Easy",
  },
];
